FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* .npmrc* ./
COPY apps/frontend/package.json apps/frontend/package.json
COPY packages/shared/package.json packages/shared/package.json
RUN npm i
COPY . .
EXPOSE 5173 4173
CMD ["npm", "-w", "@rvr/frontend", "run", "dev"]
