FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* .npmrc* ./
COPY apps/api/package.json apps/api/package.json
COPY packages/shared/package.json packages/shared/package.json
RUN npm i
COPY . .
RUN npm -w @rvr/api run build
EXPOSE 3333
CMD ["npm", "-w", "@rvr/api", "run", "start"]
